@startuml
!include style.puml
show members
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR
skinparam classAttributeFontColor #FFFFFF

Class Java.TimerTask
Class Java.Timer

Class Scheduler {
    {method} update(ScheduledTask)
}
Abstract Class ScheduledTask {
}
Class RefreshTask {
    {method} run()
}
Class ReminderPopUpTask {
    {method} run()
}

Class Meeting MODEL_COLOR
Class Java.Timer #000000
Class Java.TimerTask #000000
ScheduledTask -up-|> Java.TimerTask
RefreshTask -left-|> ScheduledTask
ReminderPopUpTask -up-|> ScheduledTask
Scheduler <--> ScheduledTask
Scheduler -right-> Java.Timer
ScheduledTask -left-> Logic
ScheduledTask -down-> Meeting

Java.Timer -[hidden]right-> Java.TimerTask
ReminderPopUpTask -[hidden]left-> Meeting
@enduml
